version: '2'
services:
	web:
		build: ./EMS-web
		image: jose/ems-web
		ports: 
		- "8081:8080"
		links:
		- "core:lookup-core"
	core:
		build: ./EMS-core
		image: jose/ems-core
		ports: 
		- "8080:8080"
		links:
		- "mongodb:mongo-web"
	mongodb:
		image: mongo
		ports:
		- "27017:27017"
		volumes:
		- /. #/srv/docker/mongodb:/var/lib/mongodb
